import type { Polecenie } from "./polecenia.types";

export const mockPolecenia: Polecenie[] = [
  {
    id: "pol-1",
    data: "2024-10-10",
    typ: "aktywne",
    polecajacyId: "prac-1",
    spolkaZrodlowa: "sellwise",
    spolkaDocelowa: "letsautomate",
    podmiotId: "pod-1",
    klientId: "kli-1",
    opis: "CTO TechVenture wspomniał o potrzebie automatyzacji CRM. Mają chaotyczne procesy w HubSpocie.",
    zrodloZgloszenieId: null,
    zgloszenieDoceloweId: "zgl-3",
    status: "wygrana",
    prowizjaNalezna: true,
  },
  {
    id: "pol-2",
    data: "2025-01-15",
    typ: "aktywne",
    polecajacyId: "prac-9",
    spolkaZrodlowa: "letsautomate",
    spolkaDocelowa: "hirewise",
    podmiotId: "pod-7",
    klientId: "kli-4",
    opis: "DataStream rozbudowuje zespół data — potrzebują rekrutacji 3 data engineerów.",
    zrodloZgloszenieId: null,
    zgloszenieDoceloweId: "zgl-6",
    status: "zakwalifikowane",
    prowizjaNalezna: true,
  },
  {
    id: "pol-3",
    data: "2025-02-08",
    typ: "przekierowanie",
    polecajacyId: "prac-6",
    spolkaZrodlowa: "finerto",
    spolkaDocelowa: "sellwise",
    podmiotId: "pod-8",
    klientId: "kli-5",
    opis: "NovaTrade podczas rozmów o podatku wspomniał o problemach ze sprzedażą — to raczej dla SellWise.",
    zrodloZgloszenieId: null,
    zgloszenieDoceloweId: "zgl-10",
    status: "zakwalifikowane",
    prowizjaNalezna: false,
  },
  {
    id: "pol-4",
    data: "2025-02-13",
    typ: "aktywne",
    polecajacyId: "prac-7",
    spolkaZrodlowa: "sellwise",
    spolkaDocelowa: "finerto",
    podmiotId: "pod-3",
    klientId: "kli-2",
    opis: "ProBuild ma chaotyczną księgowość i potrzebuje optymalizacji podatkowej. Polecam Finerto.",
    zrodloZgloszenieId: "zgl-2",
    zgloszenieDoceloweId: "zgl-14",
    status: "przeslane_do_crm",
    prowizjaNalezna: true,
  },
  {
    id: "pol-5",
    data: "2025-02-20",
    typ: "aktywne",
    polecajacyId: "prac-4",
    spolkaZrodlowa: "adwise",
    spolkaDocelowa: "finerto",
    podmiotId: "pod-4",
    klientId: null,
    opis: "Klient AdWise zapytał o pomoc prawną przy umowach z partnerami zagranicznymi.",
    zrodloZgloszenieId: "zgl-4",
    zgloszenieDoceloweId: "zgl-15",
    status: "przeslane_do_crm",
    prowizjaNalezna: true,
  },
];
