import type { Usluga } from "./uslugi.types";

export const mockUslugi: Usluga[] = [
  {
    id: "usl-1",
    nazwa: "Konsulting sprzedażowy",
    spolka: "sellwise",
    typ: "abonamentowa",
    opis: "Doradztwo strategiczne w obszarze procesów sprzedaży B2B.",
  },
  {
    id: "usl-2",
    nazwa: "Szkolenie zespołu sprzedaży",
    spolka: "sellwise",
    typ: "jednorazowa",
    opis: "Intensywne warsztaty z technik sprzedaży i negocjacji.",
  },
  {
    id: "usl-3",
    nazwa: "Audyt procesu sprzedaży",
    spolka: "sellwise",
    typ: "jednorazowa",
    opis: "Kompleksowa analiza i optymalizacja procesu sprzedaży.",
  },
  {
    id: "usl-4",
    nazwa: "Pozycjonowanie SEO",
    spolka: "adwise",
    typ: "abonamentowa",
    opis: "Pozycjonowanie strony w wynikach wyszukiwania Google.",
  },
  {
    id: "usl-5",
    nazwa: "Kampanie Google Ads",
    spolka: "adwise",
    typ: "abonamentowa",
    opis: "Zarządzanie kampaniami reklamowymi w Google Ads.",
  },
  {
    id: "usl-6",
    nazwa: "Strona internetowa B2B",
    spolka: "adwise",
    typ: "jednorazowa",
    opis: "Projektowanie i wdrożenie strony internetowej nastawionej na generowanie leadów.",
  },
  {
    id: "usl-7",
    nazwa: "Rekrutacja specjalistów IT",
    spolka: "hirewise",
    typ: "jednorazowa",
    opis: "Kompleksowy proces rekrutacji specjalistów z branży IT.",
  },
  {
    id: "usl-8",
    nazwa: "Rekrutacja liderów",
    spolka: "hirewise",
    typ: "jednorazowa",
    opis: "Executive search dla stanowisk kierowniczych i dyrektorskich.",
  },
  {
    id: "usl-9",
    nazwa: "Wdrożenie automatyzacji CRM",
    spolka: "letsautomate",
    typ: "jednorazowa",
    opis: "Automatyzacja procesów w systemach CRM (HubSpot, Pipedrive).",
  },
  {
    id: "usl-10",
    nazwa: "Integracja systemów",
    spolka: "letsautomate",
    typ: "jednorazowa",
    opis: "Łączenie systemów biznesowych w spójny ekosystem IT.",
  },
  {
    id: "usl-11",
    nazwa: "Automatyzacja procesów biznesowych",
    spolka: "letsautomate",
    typ: "abonamentowa",
    opis: "Ciągła optymalizacja i automatyzacja procesów firmy.",
  },
  {
    id: "usl-12",
    nazwa: "Doradztwo podatkowe",
    spolka: "finerto",
    typ: "abonamentowa",
    opis: "Bieżące doradztwo w zakresie optymalizacji podatkowej.",
  },
  {
    id: "usl-13",
    nazwa: "Obsługa księgowa",
    spolka: "finerto",
    typ: "abonamentowa",
    opis: "Pełna obsługa księgowa firmy.",
  },
  {
    id: "usl-14",
    nazwa: "Obsługa prawna firm",
    spolka: "finerto",
    typ: "abonamentowa",
    opis: "Stała obsługa prawna dla firm z sektora B2B.",
  },
];
