import type { Pracownik } from "./zespol.types";

export const mockPracownicy: Pracownik[] = [
  {
    id: "prac-1",
    imie: "Jan",
    nazwisko: "Kowalski",
    email: "jan.kowalski@sellwise.pl",
    telefon: "+48 601 100 200",
    spolka: "sellwise",
    role: ["handlowiec"],
    stanowisko: "Senior Konsultant Sprzedaży",
  },
  {
    id: "prac-2",
    imie: "Anna",
    nazwisko: "Nowak",
    email: "anna.nowak@sellwise.pl",
    telefon: "+48 602 200 300",
    spolka: "sellwise",
    role: ["wykonawca"],
    stanowisko: "Trener Sprzedaży",
  },
  {
    id: "prac-3",
    imie: "Piotr",
    nazwisko: "Wiśniewski",
    email: "piotr.wisniewski@letsautomate.pl",
    telefon: "+48 603 300 400",
    spolka: "letsautomate",
    role: ["wykonawca"],
    stanowisko: "Inżynier Automatyzacji",
  },
  {
    id: "prac-4",
    imie: "Katarzyna",
    nazwisko: "Zielińska",
    email: "katarzyna.zielinska@adwise.pl",
    telefon: "+48 604 400 500",
    spolka: "adwise",
    role: ["handlowiec", "wykonawca"],
    stanowisko: "Account Director",
  },
  {
    id: "prac-5",
    imie: "Michał",
    nazwisko: "Wójcik",
    email: "michal.wojcik@hirewise.pl",
    telefon: "+48 605 500 600",
    spolka: "hirewise",
    role: ["handlowiec"],
    stanowisko: "Recruitment Manager",
  },
  {
    id: "prac-6",
    imie: "Agnieszka",
    nazwisko: "Kamińska",
    email: "agnieszka.kaminska@finerto.pl",
    telefon: "+48 606 600 700",
    spolka: "finerto",
    role: ["handlowiec"],
    stanowisko: "Doradca Podatkowy",
  },
  {
    id: "prac-7",
    imie: "Tomasz",
    nazwisko: "Lewandowski",
    email: "tomasz.lewandowski@sellwise.pl",
    telefon: "+48 607 700 800",
    spolka: "sellwise",
    role: ["handlowiec", "wykonawca"],
    stanowisko: "Konsultant ds. Procesów Sprzedaży",
  },
  {
    id: "prac-8",
    imie: "Magdalena",
    nazwisko: "Dąbrowska",
    email: "magdalena.dabrowska@adwise.pl",
    telefon: "+48 608 800 900",
    spolka: "adwise",
    role: ["wykonawca"],
    stanowisko: "Specjalista SEO",
  },
  {
    id: "prac-9",
    imie: "Robert",
    nazwisko: "Jankowski",
    email: "robert.jankowski@letsautomate.pl",
    telefon: "+48 609 900 100",
    spolka: "letsautomate",
    role: ["handlowiec"],
    stanowisko: "Business Development Manager",
  },
  {
    id: "prac-10",
    imie: "Ewa",
    nazwisko: "Mazur",
    email: "ewa.mazur@hirewise.pl",
    telefon: "+48 610 100 200",
    spolka: "hirewise",
    role: ["wykonawca"],
    stanowisko: "Senior IT Recruiter",
  },
  {
    id: "prac-11",
    imie: "Marek",
    nazwisko: "Krawczyk",
    email: "marek.krawczyk@finerto.pl",
    telefon: "+48 611 200 300",
    spolka: "finerto",
    role: ["wykonawca"],
    stanowisko: "Księgowy",
  },
  {
    id: "prac-12",
    imie: "Joanna",
    nazwisko: "Pawlak",
    email: "joanna.pawlak@letsautomate.pl",
    telefon: "+48 612 300 400",
    spolka: "letsautomate",
    role: ["wykonawca"],
    stanowisko: "AI Developer",
  },
];
