import type { Podmiot, OsobaKontaktowa } from "./podmioty.types";

export const mockPodmioty: Podmiot[] = [
  {
    id: "pod-1",
    nip: "1234567890",
    nazwa: "TechVenture Sp. z o.o.",
    adres: "ul. Marszałkowska 89, 00-693 Warszawa",
    miasto: "Warszawa",
    branza: "IT / Software",
    status: "klient",
    spolka: "sellwise",
    wspolneZSpolkami: [
      { spolka: "letsautomate", status: "klient", dataOd: "2024-10-15" },
      { spolka: "hirewise", status: "w sprzedaży", dataOd: "2025-01-20" },
    ],
  },
  {
    id: "pod-2",
    nip: "6782345678",
    nazwa: "TechVenture Digital S.A.",
    adres: "ul. Floriańska 12, 31-021 Kraków",
    miasto: "Kraków",
    branza: "IT / Software",
    status: "klient",
    spolka: "letsautomate",
    wspolneZSpolkami: [{ spolka: "sellwise", status: "klient", dataOd: "2024-06-15" }],
  },
  {
    id: "pod-3",
    nip: "9876543210",
    nazwa: "ProBuild S.A.",
    adres: "ul. Piotrkowska 45, 90-418 Kraków",
    miasto: "Kraków",
    branza: "Budownictwo",
    status: "klient",
    spolka: "sellwise",
    wspolneZSpolkami: [{ spolka: "finerto", status: "w sprzedaży", dataOd: "2025-02-13" }],
  },
  {
    id: "pod-4",
    nip: "5544332211",
    nazwa: "GreenEnergy Solutions S.A.",
    adres: "ul. Długa 78, 80-831 Gdańsk",
    miasto: "Gdańsk",
    branza: "Energetyka",
    status: "klient",
    spolka: "adwise",
    wspolneZSpolkami: [{ spolka: "finerto", status: "nowe", dataOd: "2025-02-20" }],
  },
  {
    id: "pod-5",
    nip: "8512345678",
    nazwa: "MedPharm Polska Sp. z o.o.",
    adres: "ul. Szewska 10, 50-139 Wrocław",
    miasto: "Wrocław",
    branza: "Farmacja",
    status: "lead",
    spolka: "sellwise",
    wspolneZSpolkami: [],
  },
  {
    id: "pod-6",
    nip: "6312345678",
    nazwa: "FastLogistics Sp. z o.o.",
    adres: "ul. Mikołowska 32, 40-066 Katowice",
    miasto: "Katowice",
    branza: "Logistyka",
    status: "lead",
    spolka: "hirewise",
    wspolneZSpolkami: [],
  },
  {
    id: "pod-7",
    nip: "3322114455",
    nazwa: "DataStream Sp. z o.o.",
    adres: "ul. Nowy Świat 15, 00-029 Wrocław",
    miasto: "Wrocław",
    branza: "Data / Analytics",
    status: "klient",
    spolka: "letsautomate",
    wspolneZSpolkami: [
      { spolka: "hirewise", status: "w sprzedaży", dataOd: "2025-01-20" },
      { spolka: "sellwise", status: "klient", dataOd: "2025-02-18" },
    ],
  },
  {
    id: "pod-8",
    nip: "1122334455",
    nazwa: "NovaTrade Sp. z o.o.",
    adres: "ul. Grodzka 22, 31-006 Poznań",
    miasto: "Poznań",
    branza: "Handel",
    status: "klient",
    spolka: "finerto",
    wspolneZSpolkami: [{ spolka: "sellwise", status: "w sprzedaży", dataOd: "2025-02-12" }],
  },
  {
    id: "pod-9",
    nip: "5832345678",
    nazwa: "NovaTrade Logistics Sp. z o.o.",
    adres: "ul. Gdyńska 5, 81-341 Gdynia",
    miasto: "Gdynia",
    branza: "Logistyka",
    status: "klient",
    spolka: "finerto",
    wspolneZSpolkami: [],
  },
  {
    id: "pod-10",
    nip: "6677889900",
    nazwa: "CloudNet Systems Sp. z o.o.",
    adres: "al. Jerozolimskie 120, 00-807 Warszawa",
    miasto: "Warszawa",
    branza: "IT / Cloud",
    status: "lead",
    spolka: "adwise",
    wspolneZSpolkami: [],
  },
  {
    id: "pod-11",
    nip: "7799881122",
    nazwa: "SmartHR Polska Sp. z o.o.",
    adres: "ul. Puławska 145, 02-715 Warszawa",
    miasto: "Warszawa",
    branza: "HR Tech",
    status: "lead",
    spolka: "sellwise",
    wspolneZSpolkami: [{ spolka: "letsautomate", status: "w sprzedaży", dataOd: "2025-03-10" }],
  },
  {
    id: "pod-12",
    nip: "7799881122",
    nazwa: "SmartHR Polska Sp. z o.o.",
    adres: "ul. Puławska 145, 02-715 Warszawa",
    miasto: "Warszawa",
    branza: "HR Tech",
    status: "lead",
    spolka: "letsautomate",
    wspolneZSpolkami: [{ spolka: "sellwise", status: "lead", dataOd: "2025-03-15" }],
  },
];

export const mockOsobyKontaktowe: OsobaKontaktowa[] = [
  {
    id: "osoba-1",
    podmiotId: "pod-1",
    imie: "Marek",
    nazwisko: "Zieliński",
    email: "m.zielinski@techventure.pl",
    telefon: "+48 500 100 200",
    stanowisko: "Dyrektor Sprzedaży",
  },
  {
    id: "osoba-2",
    podmiotId: "pod-1",
    imie: "Anna",
    nazwisko: "Maj",
    email: "a.maj@techventure.pl",
    telefon: "+48 500 200 300",
    stanowisko: "CTO",
  },
  {
    id: "osoba-3",
    podmiotId: "pod-2",
    imie: "Karol",
    nazwisko: "Baran",
    email: "k.baran@tvdigital.pl",
    telefon: "+48 500 300 400",
    stanowisko: "Head of Marketing",
  },
  {
    id: "osoba-4",
    podmiotId: "pod-3",
    imie: "Tomasz",
    nazwisko: "Sikora",
    email: "t.sikora@probuild.pl",
    telefon: "+48 500 400 500",
    stanowisko: "Prezes Zarządu",
  },
  {
    id: "osoba-5",
    podmiotId: "pod-3",
    imie: "Monika",
    nazwisko: "Woźniak",
    email: "m.wozniak@probuild.pl",
    telefon: "+48 500 500 600",
    stanowisko: "Dyrektor Finansowy",
  },
  {
    id: "osoba-6",
    podmiotId: "pod-4",
    imie: "Paweł",
    nazwisko: "Kaczmarek",
    email: "p.kaczmarek@greenenergy.pl",
    telefon: "+48 500 600 700",
    stanowisko: "VP Sales",
  },
  {
    id: "osoba-7",
    podmiotId: "pod-5",
    imie: "Izabela",
    nazwisko: "Grabowska",
    email: "i.grabowska@medpharm.pl",
    telefon: "+48 500 700 800",
    stanowisko: "Dyrektor Operacyjny",
  },
  {
    id: "osoba-8",
    podmiotId: "pod-6",
    imie: "Krzysztof",
    nazwisko: "Pawlak",
    email: "k.pawlak@fastlog.pl",
    telefon: "+48 500 800 900",
    stanowisko: "CEO",
  },
  {
    id: "osoba-9",
    podmiotId: "pod-7",
    imie: "Natalia",
    nazwisko: "Szymańska",
    email: "n.szymanska@datastream.pl",
    telefon: "+48 500 900 100",
    stanowisko: "Head of Data",
  },
  {
    id: "osoba-10",
    podmiotId: "pod-8",
    imie: "Łukasz",
    nazwisko: "Duda",
    email: "l.duda@novatrade.pl",
    telefon: "+48 501 100 200",
    stanowisko: "Dyrektor Handlowy",
  },
  {
    id: "osoba-11",
    podmiotId: "pod-9",
    imie: "Beata",
    nazwisko: "Lis",
    email: "b.lis@ntlogistics.pl",
    telefon: "+48 501 200 300",
    stanowisko: "Kierownik Logistyki",
  },
  {
    id: "osoba-12",
    podmiotId: "pod-10",
    imie: "Damian",
    nazwisko: "Michalski",
    email: "d.michalski@cloudnet.pl",
    telefon: "+48 501 300 400",
    stanowisko: "CTO",
  },
];
