import type { Projekt } from "./projekty.types";

export const mockProjekty: Projekt[] = [
  {
    id: "proj-1",
    nazwa: "Wdrożenie procesu sprzedaży",
    podmiotId: "pod-1",
    spolka: "sellwise",
    charakter: "staly",
    status: "aktywny",
    opiekunId: "prac-1",
    wykonawcaIds: ["prac-1", "prac-2"],
    osobyKontaktoweIds: ["osoba-1", "osoba-2"],
    uslugaIds: ["usl-1", "usl-2"],
    zakres: "Audyt procesu sprzedaży, szkolenia zespołu, wdrożenie CRM",
    dataOd: "2024-06-15",
    dataDo: null,
  },
  {
    id: "proj-2",
    nazwa: "Budowa procesu sprzedaży B2B",
    podmiotId: "pod-3",
    spolka: "sellwise",
    charakter: "jednorazowy",
    status: "aktywny",
    opiekunId: "prac-7",
    wykonawcaIds: ["prac-7"],
    osobyKontaktoweIds: ["osoba-4"],
    uslugaIds: ["usl-3", "usl-1"],
    zakres: "Zaprojektowanie procesu sprzedaży od zera dla rynku B2B",
    dataOd: "2024-09-01",
    dataDo: "2025-03-31",
  },
  {
    id: "proj-3",
    nazwa: "Automatyzacja CRM HubSpot",
    podmiotId: "pod-1",
    spolka: "letsautomate",
    charakter: "jednorazowy",
    status: "aktywny",
    opiekunId: "prac-9",
    wykonawcaIds: ["prac-3"],
    osobyKontaktoweIds: ["osoba-2"],
    uslugaIds: ["usl-9"],
    zakres: "Automatyzacja workflow w HubSpot, integracja z ERP",
    dataOd: "2024-11-01",
    dataDo: "2025-04-30",
  },
  {
    id: "proj-4",
    nazwa: "Strona www + pozycjonowanie",
    podmiotId: "pod-4",
    spolka: "adwise",
    charakter: "staly",
    status: "aktywny",
    opiekunId: "prac-4",
    wykonawcaIds: ["prac-4", "prac-8"],
    osobyKontaktoweIds: ["osoba-6"],
    uslugaIds: ["usl-4", "usl-6"],
    zakres: "Nowa strona internetowa B2B + SEO + content marketing",
    dataOd: "2025-01-10",
    dataDo: null,
  },
  {
    id: "proj-5",
    nazwa: "Obsługa księgowa i doradztwo podatkowe",
    podmiotId: "pod-8",
    spolka: "finerto",
    charakter: "staly",
    status: "aktywny",
    opiekunId: "prac-6",
    wykonawcaIds: ["prac-6", "prac-11"],
    osobyKontaktoweIds: ["osoba-10"],
    uslugaIds: ["usl-12", "usl-13"],
    zakres: "Pełna obsługa księgowa, optymalizacja podatkowa",
    dataOd: "2025-02-01",
    dataDo: null,
  },
  {
    id: "proj-6",
    nazwa: "Integracja systemów ERP",
    podmiotId: "pod-1",
    spolka: "letsautomate",
    charakter: "jednorazowy",
    status: "aktywny",
    opiekunId: "prac-9",
    wykonawcaIds: ["prac-3", "prac-12"],
    osobyKontaktoweIds: ["osoba-1"],
    uslugaIds: ["usl-10"],
    zakres: "Integracja SAP z systemem magazynowym i CRM",
    dataOd: "2025-02-01",
    dataDo: "2025-06-30",
  },
  {
    id: "proj-7",
    nazwa: "Content marketing B2B",
    podmiotId: "pod-3",
    spolka: "adwise",
    charakter: "staly",
    status: "aktywny",
    opiekunId: "prac-4",
    wykonawcaIds: ["prac-8"],
    osobyKontaktoweIds: ["osoba-5"],
    uslugaIds: ["usl-5"],
    zakres: "Strategia contentowa, produkcja treści, dystrybucja",
    dataOd: "2025-01-15",
    dataDo: null,
  },
];
