import type { Zgloszenie } from "./zgloszenia.types";

export const mockZgloszenia: Zgloszenie[] = [
  {
    id: "zgl-1",
    numer: "ZGL-2024-001",
    data: "2024-05-10",
    podmiotId: "pod-1",
    osobaKontaktowaId: "osoba-1",
    zrodlo: "formularz",
    spolka: "sellwise",
    handlowiecId: "prac-1",
    status: "jest_klientem",
    notatki: [
      { id: "n-1", data: "2024-05-10", autor: "prac-1", tresc: "Firma zainteresowana audytem procesu sprzedaży i szkoleniami." },
      { id: "n-2", data: "2024-05-12", autor: "prac-1", tresc: "Po rozmowie telefonicznej — potwierdzają zainteresowanie. Umówione spotkanie na 20.05." },
      { id: "n-cross-1", data: "2024-10-15", autor: "system", tresc: "🔔 Ponowne zgłoszenie podmiotu — Podmiot TechVenture Sp. z o.o. zgłosił się ponownie. Nowe zgłoszenie ZGL-2024-003 trafiło do spółki Let's Automate. Źródło: polecenie." },
    ],
    polecenieId: null,
    nip: "1234567890",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-2",
    numer: "ZGL-2024-002",
    data: "2024-08-20",
    podmiotId: "pod-3",
    osobaKontaktowaId: "osoba-4",
    zrodlo: "telefon",
    spolka: "sellwise",
    handlowiecId: "prac-7",
    status: "jest_klientem",
    notatki: [
      { id: "n-3", data: "2024-08-20", autor: "prac-7", tresc: "Potrzebują wsparcia w budowie procesu sprzedaży." },
    ],
    polecenieId: null,
    nip: "9876543210",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-3",
    numer: "ZGL-2024-003",
    data: "2024-10-15",
    podmiotId: "pod-1",
    osobaKontaktowaId: "osoba-2",
    zrodlo: "polecenie",
    spolka: "letsautomate",
    handlowiecId: "prac-9",
    status: "jest_klientem",
    notatki: [
      { id: "n-4", data: "2024-10-15", autor: "prac-9", tresc: "CTO TechVenture chce automatyzację CRM — polecenie od SellWise." },
      { id: "n-5", data: "2024-10-18", autor: "prac-9", tresc: "Wstępna analiza wymagań zakończona. Klient korzysta z HubSpot." },
      { id: "n-6", data: "2024-10-22", autor: "prac-1", tresc: "Potwierdzam — współpraca z TechVenture przebiega bardzo dobrze po stronie SellWise." },
    ],
    polecenieId: "pol-1",
    nip: "1234567890",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-4",
    numer: "ZGL-2024-004",
    data: "2024-12-01",
    podmiotId: "pod-4",
    osobaKontaktowaId: "osoba-6",
    zrodlo: "email",
    spolka: "adwise",
    handlowiecId: "prac-4",
    status: "jest_klientem",
    notatki: [
      { id: "n-7", data: "2024-12-01", autor: "prac-4", tresc: "Potrzebują nowej strony internetowej i pozycjonowania." },
    ],
    polecenieId: null,
    nip: "5544332211",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-5",
    numer: "ZGL-2025-001",
    data: "2025-01-05",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "hubspot",
    spolka: "finerto",
    handlowiecId: null,
    status: "w_sprzedazy",
    notatki: [
      { id: "n-8", data: "2025-01-05", autor: "system", tresc: "Zgłoszenie z HubSpot — nowy deal Finerto. NIP: 7711223344." },
    ],
    polecenieId: null,
    nip: "7711223344",

    powod_odrzucenia: null,
  },
  {
    id: "zgl-6",
    numer: "ZGL-2025-002",
    data: "2025-01-20",
    podmiotId: "pod-7",
    osobaKontaktowaId: "osoba-9",
    zrodlo: "polecenie",
    spolka: "hirewise",
    handlowiecId: "prac-5",
    status: "w_sprzedazy",
    notatki: [
      { id: "n-9", data: "2025-01-20", autor: "prac-5", tresc: "Potrzebują rekrutacji data engineerów — polecenie od Let's Automate." },
      { id: "n-10", data: "2025-01-25", autor: "prac-5", tresc: "Ustalono profil kandydata. Szukają 2 osób z doświadczeniem w Spark/Airflow." },
    ],
    polecenieId: "pol-2",
    nip: "3322114455",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-7",
    numer: "ZGL-2025-003",
    data: "2025-02-01",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "formularz",
    spolka: "sellwise",
    handlowiecId: "prac-1",
    status: "nowe",
    notatki: [
      { id: "n-11", data: "2025-02-01", autor: "prac-1", tresc: "Pierwszy kontakt — do weryfikacji potrzeb." },
    ],
    polecenieId: null,
    nip: null,
    powod_odrzucenia: null,
  },
  {
    id: "zgl-8",
    numer: "ZGL-2025-004",
    data: "2025-02-05",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "pipedrive",
    spolka: "letsautomate",
    handlowiecId: null,
    status: "w_sprzedazy",
    notatki: [
      { id: "n-12", data: "2025-02-05", autor: "system", tresc: "Nowy deal z Pipedrive — Let's Automate. Brak NIP w danych CRM." },
    ],
    polecenieId: null,
    nip: null,

    powod_odrzucenia: null,
  },
  {
    id: "zgl-9",
    numer: "ZGL-2025-005",
    data: "2025-02-10",
    podmiotId: "pod-10",
    osobaKontaktowaId: "osoba-12",
    zrodlo: "formularz",
    spolka: "adwise",
    handlowiecId: "prac-4",
    status: "odrzucone",
    notatki: [
      { id: "n-13", data: "2025-02-10", autor: "prac-4", tresc: "Firma zbyt mała, nie pasuje do profilu klientów." },
    ],
    polecenieId: null,
    nip: "6677889900",
    powod_odrzucenia: "Firma poniżej progu przychodów — zbyt mały budżet marketingowy.",
  },
  {
    id: "zgl-10",
    numer: "ZGL-2025-006",
    data: "2025-02-12",
    podmiotId: "pod-8",
    osobaKontaktowaId: "osoba-10",
    zrodlo: "polecenie",
    spolka: "sellwise",
    handlowiecId: "prac-1",
    status: "w_sprzedazy",
    notatki: [
      { id: "n-14", data: "2025-02-12", autor: "prac-1", tresc: "NovaTrade potrzebuje strategii sprzedaży — polecenie od Finerto." },
    ],
    polecenieId: "pol-3",
    nip: "1122334455",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-11",
    numer: "ZGL-2025-007",
    data: "2025-02-14",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "formularz_wisegroup",
    spolka: null,
    handlowiecId: null,
    status: "nowe",
    notatki: [
      { id: "n-15", data: "2025-02-14", autor: "system", tresc: "Zgłoszenie z formularza WiseGroup — brak przypisanej spółki. Do weryfikacji przez WiseGroup Hub." },
    ],
    polecenieId: null,
    nip: null,
    powod_odrzucenia: null,
  },
  {
    id: "zgl-12",
    numer: "ZGL-2025-008",
    data: "2025-02-20",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "hubspot",
    spolka: "finerto",
    handlowiecId: null,
    status: "przegrane",
    notatki: [
      { id: "n-16", data: "2025-02-20", autor: "system", tresc: "Deal zamknięty jako przegrany w HubSpot." },
    ],
    polecenieId: null,
    nip: "9988776655",

    powod_odrzucenia: null,
  },
  {
    id: "zgl-jest-klientem",
    numer: "ZGL-2025-010",
    data: "2025-02-18",
    podmiotId: "pod-7",
    osobaKontaktowaId: "osoba-9",
    zrodlo: "polecenie",
    spolka: "sellwise",
    handlowiecId: "prac-1",
    status: "jest_klientem",
    notatki: [
      { id: "n-jk-1", data: "2025-02-18", autor: "prac-1", tresc: "Klient kupił wstępną konsultację. Karta klienta utworzona — deal nadal aktywny." },
    ],
    polecenieId: null,
    nip: "5566778899",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-14",
    numer: "ZGL-2025-011",
    data: "2025-02-13",
    podmiotId: "pod-3",
    osobaKontaktowaId: "osoba-4",
    zrodlo: "polecenie",
    spolka: "finerto",
    handlowiecId: null,
    status: "w_sprzedazy",
    notatki: [
      { id: "n-pol-fin-1", data: "2025-02-13", autor: "system", tresc: "Polecenie od SellWise. ProBuild potrzebuje optymalizacji podatkowej." },
    ],
    polecenieId: "pol-4",
    nip: "9876543210",

    powod_odrzucenia: null,
  },
  {
    id: "zgl-15",
    numer: "ZGL-2025-012",
    data: "2025-02-20",
    podmiotId: "pod-4",
    osobaKontaktowaId: "osoba-6",
    zrodlo: "polecenie",
    spolka: "finerto",
    handlowiecId: null,
    status: "w_sprzedazy",
    notatki: [
      { id: "n-pol-fin-2", data: "2025-02-20", autor: "system", tresc: "Polecenie od AdWise. Klient zapytał o pomoc prawną przy umowach zagranicznych." },
    ],
    polecenieId: "pol-5",
    nip: "5544332211",

    powod_odrzucenia: null,
  },
  {
    id: "zgl-13",
    numer: "ZGL-2025-009",
    data: "2025-02-25",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "formularz",
    spolka: "hirewise",
    handlowiecId: "prac-5",
    status: "spam",
    notatki: [
      { id: "n-17", data: "2025-02-25", autor: "prac-5", tresc: "Wiadomość testowa, wypełnione losowymi danymi." },
    ],
    polecenieId: null,
    nip: null,
    powod_odrzucenia: null,
  },
  {
    id: "zgl-16",
    numer: "ZGL-2025-013",
    data: "2025-03-01",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "formularz_wisegroup",
    spolka: null,
    handlowiecId: null,
    status: "nowe",
    notatki: [
      { id: "n-18", data: "2025-03-01", autor: "system", tresc: "Zgłoszenie z formularza WiseGroup — firma z branży IT szuka wsparcia w rekrutacji i sprzedaży. Do weryfikacji przez WiseGroup Hub." },
    ],
    polecenieId: null,
    nip: "4455667788",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-17",
    numer: "ZGL-2025-014",
    data: "2025-03-02",
    podmiotId: null,
    osobaKontaktowaId: null,
    zrodlo: "formularz_wisegroup",
    spolka: null,
    handlowiecId: null,
    status: "nowe",
    notatki: [
      { id: "n-19", data: "2025-03-02", autor: "system", tresc: "Zgłoszenie z formularza WiseGroup — zapytanie o automatyzację procesów marketingowych. Do weryfikacji przez WiseGroup Hub." },
    ],
    polecenieId: null,
    nip: null,
    powod_odrzucenia: null,
  },
  {
    id: "zgl-18",
    numer: "ZGL-2024-005",
    data: "2024-09-20",
    podmiotId: "pod-2",
    osobaKontaktowaId: "osoba-3",
    zrodlo: "pipedrive",
    spolka: "letsautomate",
    handlowiecId: "prac-9",
    status: "jest_klientem",
    notatki: [
      { id: "n-20", data: "2024-09-20", autor: "system", tresc: "Deal z Pipedrive — TechVenture Digital. Klient potwierdził współpracę." },
    ],
    polecenieId: null,
    nip: "6782345678",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-19",
    numer: "ZGL-2024-006",
    data: "2024-12-10",
    podmiotId: "pod-8",
    osobaKontaktowaId: "osoba-10",
    zrodlo: "hubspot",
    spolka: "finerto",
    handlowiecId: "prac-6",
    status: "jest_klientem",
    notatki: [
      { id: "n-21", data: "2024-12-10", autor: "system", tresc: "Deal z HubSpot — NovaTrade. Umowa na obsługę księgową podpisana." },
    ],
    polecenieId: null,
    nip: "1122334455",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-20",
    numer: "ZGL-2024-007",
    data: "2024-12-15",
    podmiotId: "pod-9",
    osobaKontaktowaId: "osoba-11",
    zrodlo: "hubspot",
    spolka: "finerto",
    handlowiecId: "prac-6",
    status: "jest_klientem",
    notatki: [
      { id: "n-22", data: "2024-12-15", autor: "system", tresc: "Deal z HubSpot — NovaTrade Logistics. Dołączyli do umowy ramowej." },
    ],
    polecenieId: null,
    nip: "5832345678",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-21",
    numer: "ZGL-2024-008",
    data: "2024-08-01",
    podmiotId: "pod-7",
    osobaKontaktowaId: "osoba-9",
    zrodlo: "pipedrive",
    spolka: "letsautomate",
    handlowiecId: "prac-9",
    status: "jest_klientem",
    notatki: [
      { id: "n-23", data: "2024-08-01", autor: "system", tresc: "Deal z Pipedrive — DataStream. Klient potwierdził współpracę w zakresie automatyzacji." },
    ],
    polecenieId: null,
    nip: "3322114455",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-22",
    numer: "ZGL-2025-015",
    data: "2025-03-15",
    podmiotId: "pod-11",
    osobaKontaktowaId: null,
    zrodlo: "formularz",
    spolka: "sellwise",
    handlowiecId: "prac-1",
    status: "nowe",
    notatki: [
      { id: "n-24", data: "2025-03-15", autor: "prac-1", tresc: "Firma z branży HR Tech zgłosiła się przez formularz. Do weryfikacji." },
    ],
    polecenieId: null,
    nip: "7799881122",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-23",
    numer: "ZGL-2025-016",
    data: "2025-03-10",
    podmiotId: "pod-12",
    osobaKontaktowaId: null,
    zrodlo: "pipedrive",
    spolka: "letsautomate",
    handlowiecId: "prac-9",
    status: "w_sprzedazy",
    notatki: [
      { id: "n-25", data: "2025-03-10", autor: "system", tresc: "Nowy deal z Pipedrive — SmartHR Polska. Rozmowy o automatyzacji procesów rekrutacyjnych." },
    ],
    polecenieId: null,
    nip: "7799881122",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-24",
    numer: "ZGL-2025-017",
    data: "2025-03-20",
    podmiotId: "pod-5",
    osobaKontaktowaId: "osoba-7",
    zrodlo: "formularz",
    spolka: "sellwise",
    handlowiecId: "prac-1",
    status: "nowe",
    notatki: [
      { id: "n-26", data: "2025-03-20", autor: "prac-1", tresc: "Zgłoszenie z formularza — MedPharm szuka wsparcia w optymalizacji sprzedaży. Do weryfikacji potrzeb." },
    ],
    polecenieId: null,
    nip: "8512345678",
    powod_odrzucenia: null,
  },
  {
    id: "zgl-25",
    numer: "ZGL-2025-018",
    data: "2025-03-22",
    podmiotId: "pod-1",
    osobaKontaktowaId: "osoba-1",
    zrodlo: "formularz",
    spolka: "sellwise",
    handlowiecId: "prac-1",
    status: "nowe",
    notatki: [
      { id: "n-27", data: "2025-03-22", autor: "prac-1", tresc: "TechVenture zgłosił się ponownie — pytają o szkolenia dla nowego zespołu sprzedaży. Firma jest już klientem." },
    ],
    polecenieId: null,
    nip: "1234567890",
    powod_odrzucenia: null,
  },
];
